steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/ai-chat-482714/ai-chat-repo/ai-chat:latest'
      - '.'
images:
  - 'asia-northeast1-docker.pkg.dev/ai-chat-482714/ai-chat-repo/ai-chat:latest'
timeout: 1200s
