import { describe, it, expect, beforeEach, vi } from 'vitest';
import { generateSessionId, isValidSessionId } from '../session';

describe('session', () => {
  describe('generateSessionId', () => {
    it('should generate a valid UUID v4 format string', () => {
      const sessionId = generateSessionId();

      // UUID v4 format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
      const uuidV4Regex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

      expect(sessionId).toMatch(uuidV4Regex);
      expect(typeof sessionId).toBe('string');
      expect(sessionId.length).toBe(36);
    });

    it('should generate unique session IDs', () => {
      const id1 = generateSessionId();
      const id2 = generateSessionId();
      const id3 = generateSessionId();

      expect(id1).not.toBe(id2);
      expect(id2).not.toBe(id3);
      expect(id1).not.toBe(id3);

      // Also verify they're all valid
      expect(isValidSessionId(id1)).toBe(true);
      expect(isValidSessionId(id2)).toBe(true);
      expect(isValidSessionId(id3)).toBe(true);
    });

    it('should generate IDs with correct UUID version (4)', () => {
      const sessionId = generateSessionId();
      const parts = sessionId.split('-');

      // The third part should start with '4' (version 4)
      expect(parts[2][0]).toBe('4');
    });

    it('should generate IDs with correct variant bits', () => {
      const sessionId = generateSessionId();
      const parts = sessionId.split('-');

      // The fourth part should start with 8, 9, a, or b
      const firstChar = parts[3][0].toLowerCase();
      expect(['8', '9', 'a', 'b']).toContain(firstChar);
    });
  });

  describe('isValidSessionId', () => {
    it('should return true for valid UUID v4 format', () => {
      const validIds = [
        '550e8400-e29b-41d4-a716-446655440000',
        '6ba7b810-9dad-41d1-80b4-00c04fd430c8',
        '123e4567-e89b-42d3-a456-426614174000',
      ];

      validIds.forEach(id => {
        expect(isValidSessionId(id)).toBe(true);
      });
    });

    it('should return false for invalid UUID format', () => {
      const invalidIds = [
        '', // empty string
        'not-a-uuid',
        '123', // too short
        '550e8400-e29b-41d4-a716', // incomplete
        '550e8400-e29b-41d4-a716-446655440000-extra', // too long
        'g50e8400-e29b-41d4-a716-446655440000', // invalid character
        '550e8400e29b41d4a716446655440000', // missing dashes
      ];

      invalidIds.forEach(id => {
        expect(isValidSessionId(id)).toBe(false);
      });
    });

    it('should be case insensitive', () => {
      const upperCase = '550E8400-E29B-41D4-A716-446655440000';
      const lowerCase = '550e8400-e29b-41d4-a716-446655440000';
      const mixedCase = '550e8400-E29B-41d4-A716-446655440000';

      expect(isValidSessionId(upperCase)).toBe(true);
      expect(isValidSessionId(lowerCase)).toBe(true);
      expect(isValidSessionId(mixedCase)).toBe(true);
    });

    it('should validate session IDs generated by generateSessionId', () => {
      // Generate 10 random session IDs and verify they're all valid
      for (let i = 0; i < 10; i++) {
        const sessionId = generateSessionId();
        expect(isValidSessionId(sessionId)).toBe(true);
      }
    });

    it('should return false for null, undefined, or non-string values', () => {
      // @ts-expect-error - Testing invalid input
      expect(isValidSessionId(null)).toBe(false);
      // @ts-expect-error - Testing invalid input
      expect(isValidSessionId(undefined)).toBe(false);
      // @ts-expect-error - Testing invalid input
      expect(isValidSessionId(123)).toBe(false);
      // @ts-expect-error - Testing invalid input
      expect(isValidSessionId({})).toBe(false);
    });
  });
});
